spring.application.name=Backend
spring.data.mongodb.uri=${MONGODB_URI:mongodb://127.0.0.1:27017/cf_analyzer}
spring.jackson.default-property-inclusion=non_null

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# Enhanced Logging
logging.level.com.CodeforcesAnalyzer.Backend=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver.cluster=INFO
logging.level.org.mongodb.driver.connection=INFO
