spring.application.name=Backend
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/cf_analyzer
spring.jackson.default-property-inclusion=non_null

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Enhanced Logging
logging.level.com.CodeforcesAnalyzer.Backend=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver.cluster=INFO
logging.level.org.mongodb.driver.connection=INFO
